### ISSUE TITLE
Terminate batch job exits with n or N

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil-dev#1]
_From @peterennis on September 26, 2017 4:23_

The system also shows multiple prompts when using Ctrl-C

![capture176](https://user-images.githubusercontent.com/140737/30842227-ad3ac9f6-a235-11e7-83d7-9d684c70e4bb.png)

![capture179](https://user-images.githubusercontent.com/140737/30842530-a790c9b8-a237-11e7-89cf-f9ad00eaafe0.png)

_Copied from original issue: ionic-team/stencil-app-starter#11_

**Comment by jthoms1** [comment]
I can reproduce, but I don't think there is a way to work around this in windows. Fortunately you only need to answer the question one time.

**Comment by peterennis** [comment]
@jthoms1, Asking the same question multiple times is one thing.
Terminating when N is selected is another!

**Comment by jthoms1** [comment]
Ya unfortunate.  I wish this is something I could control. When you get this prompt the program has already been terminated.

**Comment by peterennis** [comment]
Could you make a trivial sample to show this problem with Windows?
Seems like it is a possible bug on their side or some hidden magic is needed.
I can then open a support ticket with MS and get their engineers to look at it
in relation to our development integration.
